[program:laravel-fpm]
command=/usr/sbin/php-fpm8.2 -F
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/laravel-fpm.out.log
stderr_logfile=/var/log/supervisor/laravel-fpm.err.log

[program:laravel-nginx]
command=/usr/sbin/nginx -c /etc/nginx/nginx-laravel.conf -g "daemon off;"
autostart=true
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/laravel-nginx.out.log
stderr_logfile=/var/log/supervisor/laravel-nginx.err.log

[program:laravel-scheduler]
command=/bin/sh -c "while true; do /usr/bin/php /app/artisan schedule:run >> /var/log/supervisor/laravel-schedule.log 2>&1; sleep 60; done"
directory=/app
autostart=true
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/laravel-scheduler.out.log
stderr_logfile=/var/log/supervisor/laravel-scheduler.err.log
